import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { join } from "node:path";
import { Kernel, encodeInput, decodeOutcome, decodeRequest, encodeResult } from "../embedding/index.mjs";
import { readBounded } from "./runtime-bundle.mjs";

const integer = n => { const b = new Uint8Array(8); new DataView(b.buffer).setBigUint64(0, BigInt(n), true); return b; };
async function instance(root, digest) {
  return Kernel.create({ bytes: await readBounded(join(root, "runtime/world-kernel.wasm")), expectedSha256: digest });
}
async function stage(root, digest, mode, state, response) {
  const k = await instance(root, digest);
  const image = await readBounded(join(root, "smoke/effect.bpi3"));
  const p = k.prepare(image);
  const s = mode === "start" ? k.start(p) : k.restore(p, Buffer.from(state, "base64"));
  k.releasePrepared(p);
  let outcome = decodeOutcome(k.drive(s, { checkpoint: true }));
  const trace = [];
  for (let i = 0; i < 32; i++) {
    if (outcome.kind === "requested") {
      const request = await decodeRequest(outcome.request);
      trace.push(request.semanticIdentity);
      if (mode === "start") {
        assert.equal(request.semanticIdentity, "example/resource-acquire");
        return { state: Buffer.from(k.checkpoint(s, { transfer: true })).toString("base64"), trace };
      }
      assert.ok(["example/resource-acquire", "example/resource-use", "example/resource-release"].includes(request.semanticIdentity));
      const value = request.semanticIdentity === "example/resource-acquire" ? integer(response) : new Uint8Array();
      // Bind to the request generated by this restored instance.
      outcome = decodeOutcome(k.drive(s, { control: "reply", value: await encodeResult(outcome.request, value), checkpoint: true }));
    } else if (outcome.kind === "progressed" || outcome.kind === "yielded") {
      outcome = decodeOutcome(k.drive(s, { control: outcome.kind === "yielded" ? "resume_yield" : "none", checkpoint: true }));
    } else {
      assert.equal(outcome.kind, "completed");
      assert.deepEqual(outcome.value, integer(BigInt(response) + 1n));
      k.close(s);
      return { value: Buffer.from(outcome.value).toString("hex"), trace };
    }
  }
  throw new Error("smoke exceeded 32 boundaries");
}
export async function runSmoke(root, digest) {
  const k = await instance(root, digest);
  const input = encodeInput({ image: await readBounded(join(root, "smoke/pure.bpi3")), initialArgs: new Uint8Array() });
  assert.deepEqual(new Uint8Array(await readBounded(join(root, "smoke/pure.pki3"))), input);
  const pure = decodeOutcome(k.invoke(input));
  assert.equal(pure.kind, "completed");
  assert.deepEqual(pure.value, integer(2080));
  const cli = join(root, "runtime/bin/world.mjs");
  assert.match(execFileSync(process.execPath, [cli, "--version"], { encoding: "utf8", timeout: 30000 }), /^6\.0\.0-dev\.0\s*$/);
  const cliResult = execFileSync(process.execPath, [cli, "invoke", "--kernel", join(root, "runtime/world-kernel.wasm"), "--sha256", digest, "--input", join(root, "smoke/pure.pki3")], { timeout: 30000 });
  assert.deepEqual(decodeOutcome(cliResult).value, integer(2080));
  if (process.platform !== "win32") {
    const direct = execFileSync(cli, ["invoke", "--kernel", join(root, "runtime/world-kernel.wasm"),
      "--sha256", digest, "--input", join(root, "smoke/pure.pki3")], { timeout: 30000 });
    assert.deepEqual(direct, cliResult);
  }
  const worker = join(root, "runtime/src/node/runtime-smoke.mjs");
  const call = args => JSON.parse(execFileSync(process.execPath, [worker, root, digest, ...args], {
    encoding: "utf8", timeout: 30000, maxBuffer: 2 << 20,
  }));
  const parked = call(["start"]); // This process exits before either restoration.
  const results = [41, 52].map(reply => call(["restore", parked.state, String(reply)]));
  assert.notEqual(results[0].value, results[1].value);
  for (const result of results) assert.deepEqual(result.trace, ["example/resource-acquire", "example/resource-use", "example/resource-release"]);
  return { pure: 2080, replies: [41, 52], results: [42, 53], freshProcessRestoration: true };
}
if (import.meta.main) {
  const [root, digest, mode, state, response] = process.argv.slice(2);
  console.log(JSON.stringify(await stage(root, digest, mode, state, response)));
}
